version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: mudar123
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: mudar123

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ../.:/var/www/html
      - ../wp-content:/var/www/html/wp-content
      - ./docker-files/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8500:80"
    networks:
      - webnet
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dev
      WORDPRESS_DB_PASSWORD: mudar123
      WORDPRESS_DB_NAME: dev
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_TABLE_PREFIX: 'wpp4_'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks:
      - webnet
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100000000
    restart: always
    ports:
      - 8084:80

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ../montagem:/usr/share/nginx/html
      - ./docker-files/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  webnet:
    driver: bridge
